### PR TITLE
Add zig language support

### PR DESCRIPTION
**Pull request by typesafe**
I wanted to start the "build your own git" using Zig, but noticed the language was not supported... yet.

I hope this PR will fix that. 🙂

### CODE REVIEW

**Comment by typesafe** [comment]
I've noticed the failed test. Fixed the `your_git.sh` script to account for temporary directory.

PS: I could not get `course-sdk test zig` to work locally (MacOS) I'll dive deeper to see if I can fix that.

**Comment by typesafe** [comment]
For got to run 🤦 `course-sdk compile zig`. Generated files are now included.

**Comment by ryan-gang** [comment]
Nice work @typesafe! All tests seem to be passing.
Will try to review this and merge when I get some time.

**Comment by ryan-gang** [comment]
Hey @typesafe, I have deployed this to production, and added you as an alpha-tester. You should be able to go and do the git challenge in zig now. 
Let me know if you face any issues.

**Comment by typesafe** [comment]
Hey @ryan-gang, thanks for merging and deploying. 

Quick update: I've reached the final stage without any issues. I thought, I'd let you know now, since this last stage will take a bit more time than the others it seems 😅.

**Comment by ryan-gang** [comment]
Nice going @typesafe!
BTW, if it helps I have a document listing the steps for the last stage in quite some detail here: https://github.com/ryan-gang/build-your-own-git/blob/master/git-protocol-pack.md

**Pull request merged**
